pipeline {
    agent {
        node {
            label 'k8s'
        }
    }

    environment{
        DOCKER_TAG = getDockerTag()
    }

    stages{

        stage('Build Image'){
            steps{
                sh "docker build -f build/Dockerfile . -t registry.com:5000/app2:${DOCKER_TAG}"
            }
        }

        stage('Push Image'){
            steps{
                sh "docker push registry.com:5000/app2:${DOCKER_TAG}"
        }
    }

        stage('Remove Image'){
            steps{
                sh "docker rmi registry.com:5000/app2:${DOCKER_TAG}"
            }
        }

        stage('Deploy to k8s'){
            steps{
            sh "chmod +x changeTag.sh"
            sh "./changeTag.sh ${DOCKER_TAG}"
            sh " kubectl apply -f ./deploy/app2-deployment-svc-tag.yaml"
            }
        }
    }
}

//
def getDockerTag(){
    def tag = sh script: 'git rev-parse HEAD', returnStdout: true
    return tag
}
